pipeline {
    agent any
    stages {    
        stage('Checkout Scm') {
            steps {
                git 'https://github.com/JynLeazy/java-maven.git'
            }
        }
        
        stage('javadoc') {
            steps {                
                sh '''
                cd src/main/java/com/mycompany/app/
                javadoc App.java'''
            }
        }        
    }
    post {
        always {
            echo 'No converter for Publisher: hudson.tasks.JavadocArchiver'
        }
    }
}
