pipeline {
    agent any
    stages {            
        stage('javadoc') {
            steps {                
                sh '''
                mkdir -p javadoc/
                cd javadoc/
                javadoc ../src//main/java/com/mycompany/app/App.java
                mvn clean compile pmd:pmd checkstyle:checkstyle findbugs:findbugs
                '''
                javadoc javadocDir: 'javadoc', keepAll: false
                recordIssues(tools: [checkStyle(pattern: 'target/checkstyle-result.xml'), pmdParser(pattern: 'target/pmd.xml'), findBugs(pattern: 'target/findbugsXml.xml', useRankAsPriority: true)])
            }
        }        
    }
}
