pipeline {
    agent any
    stages {            
        stage('javadoc') {
            steps {
                // Clean before build
                cleanWs()
                sh '''
                mkdir -p javadoc/
                cd javadoc/
                javadoc ../src//main/java/com/mycompany/app/App.java
                mvn clean compile pmd:pmd checkstyle:checkstyle findbugs:findbugs
                '''
                javadoc javadocDir: 'javadoc', keepAll: false
                junit 'tarjet/surefire-reports/*.xml'
                recordIssues(tools: [checkStyle(pattern: 'target/checkstyle-result.xml'), pmdParser(pattern: 'target/pmd.xml'), findBugs(pattern: 'target/findbugsXml.xml', useRankAsPriority: true)])
            }
        }        
    }
    post {
    // Clean after build
        always {
            cleanWs(cleanWhenNotBuilt: false,
                    deleteDirs: true,
                    disableDeferredWipeout: true,
                    notFailBuild: true,
                    patterns: [[pattern: '.gitignore', type: 'INCLUDE'],
                               [pattern: '.propsfile', type: 'EXCLUDE']])
        }
    }
}
